version: '3'

services:
  authentication:
    build:
      context: ./authentication
    ports:
      - "4001:4001"
    environment:
      - DB_HOST=mongodb
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=bufferOverflow
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    depends_on:
      - auth-mongodb
    networks:
      - app-network

  auth-mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db
    networks:
      - app-network

  post:
    build:
      context: ./post
    container_name: post-container1
    environment:
      - DB_HOST=post-mongodb
      - DB_USER1=user
      - DB_PASSWORD1=pass
      - POST_DB_NAME=bufferOverflow1
    ports:
      - "4002:4002"
    depends_on:
      - post-mongodb
      - minio
    networks:
      - app-network

  post-mongodb:
    image: mongo:latest
    container_name: post-mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27018:27017"
    volumes:
      - post_data:/data/db
    networks:
      - app-network

  notification:
    build:
      context: ./notification
    container_name: notification
    environment:
      - DB_HOST=notification-mongodb
      - DB_USER=user
      - DB_PASSWORD=pass
      - NOTIFICATION_DB_NAME=bufferOverflow2
    ports:
      - "4003:4003"
    depends_on:
      - notification-mongodb
    networks:
      - app-network

  notification-mongodb:
    image: mongo:latest
    container_name: notification-mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27019:27017"
    volumes:
      - notification_data:/data/db
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - authentication
      - notification
      - post
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth_data:
  post_data:
  notification_data:
  minio_data:
